# ── Base de données PostgreSQL (Railway) ─────────────────────────────────────
spring.datasource.url=jdbc:postgresql://postgres.railway.internal:5432/railway
spring.datasource.username=postgres
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ── H2 désactivé en production ────────────────────────────────────────────────
spring.h2.console.enabled=false

# ── Port (Railway l'injecte automatiquement) ─────────────────────────────────
server.port=${PORT:8080}
